name: angel
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    # (this is just an example, not intended to be a production configuration)
  angel_eater:
    depends_on:
      - db
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ./.debug/Recordings:/app/Recordings
      - ./.debug/Output:/app/Output

        