name: angel-archiver
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  archiver:
    depends_on:
      - db
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ./.debug/Recordings:/app/Recordings
      - ./.debug/Output:/app/Output

        